spring.application.name=Plano_Odondologico
spring.datasource.url=jdbc:postgresql://localhost:5432/clinica_odontologica
spring.datasource.username=postgres
spring.datasource.password=lucas2010

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.thymeleaf.cache=false